name: flutter_animations
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_circular_text: ^0.3.1
  cached_network_image: ^3.2.2
  audio_video_progress_bar: ^0.11.0
  just_audio: ^0.9.30
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:     
         - assets/
        #  - assets/images/
         - assets/audio/